
export const VIEW_BRACOCONTRAIDO = "Braço Contraído"
export const VIEW_BRACORELAXADO = "Braço Relaxado"
export const VIEW_ANTEBRACO = "Antebraço"
export const VIEW_PUNHO = "Punho"
export const VIEW_COXAPROXIMAL = "Coxa proximal"
export const VIEW_PERNA = "Perna"
export const VIEW_PESO = "Peso"
export const VIEW_PESCOCO = "Pescoço"
export const VIEW_OMBRO = "Ombro"
export const VIEW_PEITORAL = "Peitoral"
export const VIEW_ABDOMEN = "Abdômen"
export const VIEW_CINTURA = "Cintura"
export const VIEW_QUADRIL = "Quadril"
export const VIEW_DATA = "Data"
